export { default as DiffDemo } from './diffdemo/DiffDemo.vue'
export { default as DiscoElysiumThoughts } from './discoelysiumthoughts/DiscoElysiumThoughts.vue'
export { default as EndymionThoughts } from './endymionthoughts/EndymionThoughts.vue'
export { default as Psychohistory } from './psychohistory/Psychohistory.vue'
export { default as TikTokSadness } from './tiktoksadness/TikTokSadness.vue'
